SELECT A.ROLL_NUMBER, A.NAME
FROM STUDENT_INFORMATION A
JOIN EXAMINATION_MARKS B
ON A.ROLL_NUMBER = B.ROLL_NUMBER 
GROUP BY B.ROLL_NUMBER
HAVING SUM(B.SUBJECT_ONE + B.SUBJECT_TWO + B.SUBJECT_THREE) < 100;